# Generated by Django 5.0.4 on 2024-12-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shippment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='uuid',
            field=models.CharField(blank=True, default='6f158551511d', max_length=50, null=True),
        ),
    ]
